name: frontiershu

services:
  app:
    type: compose
    app_mount: delegated
    scanner: false
    services:
      image: kaszarobert/hedgelib:latest
      command: tail -f /dev/null

tooling:
  HedgeArcPack:
    service: app

  PuyoTextEditor:
    service: app

  process_pac_files:
    service: app
    cmd:
      - app: "/app/.lando/process_pac_files.sh /app/0src /app/1converted"

  copy_files_recursive:
    service: app
    cmd:
      - app: "/app/.lando/copy_files_recursive.sh /app/1converted/ /app/2xml"

  convert_xmls_to_cnvrs_back:
    service: app
    cmd:
      - app: "/app/.lando/convert_xmls_to_cnvrs_back.sh /app/2xml/ /app/3cnvrs"

  convert_back_to_pac:
    service: app
    cmd:
      - app: "/app/.lando/convert_back_to_pac.sh /app/3cnvrs /app/4newpac"